### ISSUE TITLE
No videos available for Tests 2+

### ISSUE THREAD

**Issue by thecodemaiden** [JoaoDiogoFalcao/AutoCheckout#6]
Hi hi,

We are ready to do some fusion between weight and vision, but there are no videos available for those cases. When will the video be available?

**Comment by JoaoDiogoFalcao** [comment]
Hi, 
There is a script that allows you to build the videos off of the frames inside the DB. 
https://github.com/JoaoDiogoFalcao/AutoCheckout/blob/master/RGBFrame_to_mp4.py

They were not explicitly extracted for all tests, but you can extract them.

**Comment by thecodemaiden** [comment]
Thanks,

Where are the pickle (.pkl) files used in RGBFrame_to_mp4.py located?

**Comment by thecodemaiden** [comment]
I wrote my own script to extract the frames directly from the repository; I'm closing this issue.
